### PR TITLE
zemu nano x support

### PR DESCRIPTION
**Pull request by rllola**
- [x] Fix Makefile to create nanos and x app
- [x] Update test to run on nano S and X
- [x] Added x snapshot
- [x] Fixed test
- ~~[ ] Support nao x for ledgeracio too~~

### CODE REVIEW

**Comment by jleni** [comment]
@rllola sorry for rebasing but we had to take changes that Ledger recently made in their fork.

**Comment by rllola** [comment]
The failing nano x test seems to come from this part of the app : 
https://github.com/Zondax/ledger-polkadot/blob/master/app/src/apdu_handler.c#L319-L321
app/src/apdu_handler.c:319-321

It is working normally with nano s but unfortunately not with nano x. It is unclear why for the moment.

**Comment by jleni** [comment]
Depends on https://github.com/LedgerHQ/speculos/issues/130

**Comment by rllola** [comment]
I am still updating the zemu nano x tests. I have however an issue with the delay between the actions. It seems to display a page it is a bit more long than other and it will not count a right click (because it is happening too fast).

Should we have zemu wait for the display to change instead of arbitrary delay between click ?

**Comment by rllola** [comment]
Might be another issue. It looks like when we are going backward and we have multiple pages (e.g address) it will not go back to [2/2] but directly to [1/2].

Not sure if intended or not.

**Comment by jleni** [comment]
yes, going backwards works differently in Nano X.. I could not fix that

**Comment by jleni** [comment]
btw, you can look at the Kusama app v28.  I fixed a lot of the issues here.
I think it is a good reference now for a clean version.

**Comment by rllola** [comment]
Depends on this : https://github.com/LedgerHQ/speculos/issues/134

**Comment by rllola** [comment]
I think we can merge this. It has ready to go nano x tests but I have deactivated it regarding the speculos issue we have. We should open a new PR once it is fixed. This one has become quite big already.

**Pull request merged**
